# Generated by Django 5.2.1 on 2026-08-15 20:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espessura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milimetros', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'espessuras',
                'ordering': ['milimetros'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('preco_m2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'db_table': 'materiais',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('base_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('altura_mm', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'tamanhos',
                'ordering': ['base_mm', 'altura_mm'],
            },
        ),
        migrations.CreateModel(
            name='TipoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_base', models.CharField(max_length=100, unique=True)),
                ('fator_base', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'db_table': 'tipos_bases',
                'ordering': ['nome_base'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orcamento', models.CharField(max_length=120)),
                ('data_orcamento', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('detalhes_json', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('espessura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='base.espessura')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='base.material')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='base.tamanho')),
                ('tipo_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='base.tipobase')),
            ],
            options={
                'db_table': 'orcamentos',
                'ordering': ['-data_orcamento', '-id'],
            },
        ),
    ]
