# Generated by Django 5.2.1 on 2026-08-16 01:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def popular_fatores_por_tamanho(apps, schema_editor):
    TipoBase = apps.get_model("base", "TipoBase")
    Tamanho = apps.get_model("base", "Tamanho")
    FatorBaseTamanho = apps.get_model("base", "FatorBaseTamanho")

    for tipo_base in TipoBase.objects.all():
        for tamanho in Tamanho.objects.all():
            FatorBaseTamanho.objects.update_or_create(
                tipo_base=tipo_base,
                tamanho=tamanho,
                defaults={"fator_base": tipo_base.fator_base},
            )


def reverter_fatores_por_tamanho(apps, schema_editor):
    FatorBaseTamanho = apps.get_model("base", "FatorBaseTamanho")
    FatorBaseTamanho.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatorBaseTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator_base', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatores_tipo_base', to='base.tamanho')),
                ('tipo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatores_por_tamanho', to='base.tipobase')),
            ],
            options={
                'db_table': 'fatores_base_tamanho',
                'ordering': ['tipo_base__nome_base', 'tamanho__base_mm', 'tamanho__altura_mm'],
                'constraints': [models.UniqueConstraint(fields=('tipo_base', 'tamanho'), name='unique_tipo_base_tamanho')],
            },
        ),
        migrations.RunPython(popular_fatores_por_tamanho, reverter_fatores_por_tamanho),
        migrations.RemoveField(
            model_name='tipobase',
            name='fator_base',
        ),
    ]
