# Generated by Django 5.2.1 on 2026-08-16 12:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def popular_faixas_iniciais(apps, schema_editor):
    DescontoQuantidade = apps.get_model("base", "DescontoQuantidade")
    faixas = [
        {"quantidade_min": 1, "quantidade_max": 10, "fator_desconto": Decimal("1.00")},
        {"quantidade_min": 11, "quantidade_max": 20, "fator_desconto": Decimal("0.95")},
        {"quantidade_min": 21, "quantidade_max": None, "fator_desconto": Decimal("0.90")},
    ]
    for faixa in faixas:
        DescontoQuantidade.objects.update_or_create(
            quantidade_min=faixa["quantidade_min"],
            quantidade_max=faixa["quantidade_max"],
            defaults={"fator_desconto": faixa["fator_desconto"]},
        )


def reverter_faixas_iniciais(apps, schema_editor):
    DescontoQuantidade = apps.get_model("base", "DescontoQuantidade")
    DescontoQuantidade.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_tipobase_fator_base_fatorbasetamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescontoQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantidade_max', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para uma faixa sem limite superior.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fator_desconto', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'db_table': 'descontos_quantidade',
                'ordering': ['quantidade_min', 'id'],
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(popular_faixas_iniciais, reverter_faixas_iniciais),
    ]
