from django.urls import path

from .views import (
    AdminDashboardView,
    AdminLoginView,
    AdminLogoutView,
    EspessuraCreateView,
    EspessuraDeleteView,
    EspessuraListView,
    EspessuraUpdateView,
    FatorBaseTamanhoCreateView,
    FatorBaseTamanhoDeleteView,
    FatorBaseTamanhoListView,
    FatorBaseTamanhoUpdateView,
    MaterialCreateView,
    MaterialDeleteView,
    MaterialListView,
    MaterialUpdateView,
    OrcamentoCalcularView,
    OrcamentoSalvarView,
    PublicHomeView,
    TamanhoCreateView,
    TamanhoDeleteView,
    TamanhoListView,
    TamanhoUpdateView,
    TipoBaseCreateView,
    TipoBaseDeleteView,
    TipoBaseListView,
    TipoBaseUpdateView,
)


urlpatterns = [
    path("", PublicHomeView.as_view(), name="public_home"),
    path("orcamentos/calcular/", OrcamentoCalcularView.as_view(), name="public_orcamento_calcular"),
    path("orcamentos/salvar/", OrcamentoSalvarView.as_view(), name="public_orcamento_salvar"),
    path("admin/login/", AdminLoginView.as_view(), name="admin_login"),
    path("admin/logout/", AdminLogoutView.as_view(), name="admin_logout"),
    path("admin/", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("admin/tamanhos/", TamanhoListView.as_view(), name="admin_tamanho_list"),
    path("admin/tamanhos/novo/", TamanhoCreateView.as_view(), name="admin_tamanho_create"),
    path("admin/tamanhos/<int:pk>/editar/", TamanhoUpdateView.as_view(), name="admin_tamanho_update"),
    path("admin/tamanhos/<int:pk>/excluir/", TamanhoDeleteView.as_view(), name="admin_tamanho_delete"),
    path("admin/espessuras/", EspessuraListView.as_view(), name="admin_espessura_list"),
    path("admin/espessuras/nova/", EspessuraCreateView.as_view(), name="admin_espessura_create"),
    path("admin/espessuras/<int:pk>/editar/", EspessuraUpdateView.as_view(), name="admin_espessura_update"),
    path("admin/espessuras/<int:pk>/excluir/", EspessuraDeleteView.as_view(), name="admin_espessura_delete"),
    path("admin/materiais/", MaterialListView.as_view(), name="admin_material_list"),
    path("admin/materiais/novo/", MaterialCreateView.as_view(), name="admin_material_create"),
    path("admin/materiais/<int:pk>/editar/", MaterialUpdateView.as_view(), name="admin_material_update"),
    path("admin/materiais/<int:pk>/excluir/", MaterialDeleteView.as_view(), name="admin_material_delete"),
    path("admin/tipos-base/", TipoBaseListView.as_view(), name="admin_tipo_base_list"),
    path("admin/tipos-base/novo/", TipoBaseCreateView.as_view(), name="admin_tipo_base_create"),
    path("admin/tipos-base/<int:pk>/editar/", TipoBaseUpdateView.as_view(), name="admin_tipo_base_update"),
    path("admin/tipos-base/<int:pk>/excluir/", TipoBaseDeleteView.as_view(), name="admin_tipo_base_delete"),
    path("admin/fatores-base/", FatorBaseTamanhoListView.as_view(), name="admin_fator_base_tamanho_list"),
    path("admin/fatores-base/novo/", FatorBaseTamanhoCreateView.as_view(), name="admin_fator_base_tamanho_create"),
    path("admin/fatores-base/<int:pk>/editar/", FatorBaseTamanhoUpdateView.as_view(), name="admin_fator_base_tamanho_update"),
    path("admin/fatores-base/<int:pk>/excluir/", FatorBaseTamanhoDeleteView.as_view(), name="admin_fator_base_tamanho_delete"),
]
